### PR TITLE
macOS wxWidgets 3.1.5 universal binary

### PR DESCRIPTION
**Pull request by sjanzou**

### CODE REVIEW

**Review by dguittet — APPROVED** [review]
Looks good to me, just needs cleaned comments before merging.

**Review by brtietz — CHANGES_REQUESTED** [review]
I got two warnings about deprecated code while building on Linux:

Depricated Functions:

/home/brian/sam_dev/wex/src/codeedit.cpp: In member function ‘void wxCodeEditCtrl::SetLanguage(wxCodeEditCtrl::Language)’:
/home/brian/sam_dev/wex/src/codeedit.cpp:306:19: warning: ‘void wxStyledTextCtrl::SetStyleBits(int)’ is deprecated: This method uses a function deprecated in the Scintilla library. [-Wdeprecated-declarations]
  306 |     SetStyleBits(8);
      |                   ^
In file included from /home/brian/sam_dev/wex/src/../include/wex/codeedit.h:37,
                 from /home/brian/sam_dev/wex/src/codeedit.cpp:31:
/home/brian/wx-3.1.5/include/wx-3.1/wx/stc/stc.h:3349:10: note: declared here
 3349 |     void SetStyleBits(int bits);
      | 

In file included from /home/brian/sam_dev/wex/src/pdf/pdfprint.cpp:61:
/home/brian/sam_dev/wex/src/../include/wex/pdf/pdfprint.h: In member function ‘virtual void wxPdfPreviewDCImpl::DoGetClippingBox(wxCoord*, wxCoord*, wxCoord*, wxCoord*) const’:
/home/brian/sam_dev/wex/src/../include/wex/pdf/pdfprint.h:747:41: warning: ‘virtual void wxDCImpl::DoGetClippingBox(wxCoord*, wxCoord*, wxCoord*, wxCoord*) const’ is deprecated [-Wdeprecated-declarations]
  747 |         m_dc.DoGetClippingBox(x, y, w, h);
      |                                         ^
In file included from /home/brian/wx-3.1.5/include/wx-3.1/wx/wxprec.h:12,
                 from /home/brian/sam_dev/wex/src/pdf/pdfprint.cpp:13:
/home/brian/wx-3.1.5/include/wx-3.1/wx/dc.h:468:5: note: declared here
  468 |     wxDEPRECATED_BUT_USED_INTERNALLY(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Are those worth addressing as a part of this update?

**Comment by sjanzou** [comment]
> I got two warnings about deprecated code while building on Linux:
> 
> Depricated Functions:
> 
> /home/brian/sam_dev/wex/src/codeedit.cpp: In member function ‘void wxCodeEditCtrl::SetLanguage(wxCodeEditCtrl::Language)’: /home/brian/sam_dev/wex/src/codeedit.cpp:306:19: warning: ‘void wxStyledTextCtrl::SetStyleBits(int)’ is deprecated: This method uses a function deprecated in the Scintilla library. [-Wdeprecated-declarations] 306 | SetStyleBits(8); | ^ In file included from /home/brian/sam_dev/wex/src/../include/wex/codeedit.h:37, from /home/brian/sam_dev/wex/src/codeedit.cpp:31: /home/brian/wx-3.1.5/include/wx-3.1/wx/stc/stc.h:3349:10: note: declared here 3349 | void SetStyleBits(int bits); |
> 
> In file included from /home/brian/sam_dev/wex/src/pdf/pdfprint.cpp:61: /home/brian/sam_dev/wex/src/../include/wex/pdf/pdfprint.h: In member function ‘virtual void wxPdfPreviewDCImpl::DoGetClippingBox(wxCoord*, wxCoord*, wxCoord*, wxCoord*) const’: /home/brian/sam_dev/wex/src/../include/wex/pdf/pdfprint.h:747:41: warning: ‘virtual void wxDCImpl::DoGetClippingBox(wxCoord*, wxCoord*, wxCoord*, wxCoord*) const’ is deprecated [-Wdeprecated-declarations] 747 | m_dc.DoGetClippingBox(x, y, w, h); | ^ In file included from /home/brian/wx-3.1.5/include/wx-3.1/wx/wxprec.h:12, from /home/brian/sam_dev/wex/src/pdf/pdfprint.cpp:13: /home/brian/wx-3.1.5/include/wx-3.1/wx/dc.h:468:5: note: declared here 468 | wxDEPRECATED_BUT_USED_INTERNALLY( | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> Are those worth addressing as a part of this update?

I will take care of those two deprecated issues in the next commit...
For reference, macOS seems to throw the most warnings and a quick scan shows some overlap with the Checkmarx scans. So, if we have time we can start addressing the issues from building on macOS 12.0.1:
image

**Comment by sjanzou** [comment]
> I got two warnings about deprecated code while building on Linux:
> 
> Depricated Functions:
> 
> /home/brian/sam_dev/wex/src/codeedit.cpp: In member function ‘void wxCodeEditCtrl::SetLanguage(wxCodeEditCtrl::Language)’: /home/brian/sam_dev/wex/src/codeedit.cpp:306:19: warning: ‘void wxStyledTextCtrl::SetStyleBits(int)’ is deprecated: This method uses a function deprecated in the Scintilla library. [-Wdeprecated-declarations] 306 | SetStyleBits(8); | ^ In file included from /home/brian/sam_dev/wex/src/../include/wex/codeedit.h:37, from /home/brian/sam_dev/wex/src/codeedit.cpp:31: /home/brian/wx-3.1.5/include/wx-3.1/wx/stc/stc.h:3349:10: note: declared here 3349 | void SetStyleBits(int bits); |
> 
> In file included from /home/brian/sam_dev/wex/src/pdf/pdfprint.cpp:61: /home/brian/sam_dev/wex/src/../include/wex/pdf/pdfprint.h: In member function ‘virtual void wxPdfPreviewDCImpl::DoGetClippingBox(wxCoord*, wxCoord*, wxCoord*, wxCoord*) const’: /home/brian/sam_dev/wex/src/../include/wex/pdf/pdfprint.h:747:41: warning: ‘virtual void wxDCImpl::DoGetClippingBox(wxCoord*, wxCoord*, wxCoord*, wxCoord*) const’ is deprecated [-Wdeprecated-declarations] 747 | m_dc.DoGetClippingBox(x, y, w, h); | ^ In file included from /home/brian/wx-3.1.5/include/wx-3.1/wx/wxprec.h:12, from /home/brian/sam_dev/wex/src/pdf/pdfprint.cpp:13: /home/brian/wx-3.1.5/include/wx-3.1/wx/dc.h:468:5: note: declared here 468 | wxDEPRECATED_BUT_USED_INTERNALLY( | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> Are those worth addressing as a part of this update?

Fixed in b60ec07eee8df84935a34c6a24d1aeabe895cfb2

**Review by brtietz — APPROVED** [review]
Last night's pushes removed the warning when I built this morning. Thanks!

**Review by janinefreeman — APPROVED** [review]
Works for me on Windows

**Pull request merged**
