### PR TITLE
Update renderer for crisper plot axes and titles per SAM issue 883

### PR DESCRIPTION
**Pull request by sjanzou**

### CODE REVIEW

**Comment by sjanzou** [comment]
Updated wxGraphicsContext to best quality since reset from wx3.1.1 and plot quality matching with 2021.12.02 release
image

**Comment by sjanzou** [comment]
Addresses SAM issue 883 https://github.com/NREL/SAM/issues/883

**Comment by mjprilliman** [comment]
@sjanzou are your results with this wex branch and everything else on patch? I am having trouble replicating the results on my Windows machine 
image

**Comment by sjanzou** [comment]
> @sjanzou are your results with this wex branch and everything else on patch? I am having trouble replicating the results on my Windows machine image

@mjprilliman, can you attach your SAM file used to generate this and what resolution and magnification on your display are you using?

**Comment by mjprilliman** [comment]
> > @sjanzou are your results with this wex branch and everything else on patch? I am having trouble replicating the results on my Windows machine image
> 
> @mjprilliman, can you attach your SAM file used to generate this and what resolution and magnification on your display are you using?
[Graphics_test.zip](https://github.com/NREL/wex/files/7892282/Graphics_test.zip)

image

Not sure about magnification, I don't have any Magnifiers on in Windows.

**Comment by sjanzou** [comment]
> > > @sjanzou are your results with this wex branch and everything else on patch? I am having trouble replicating the results on my Windows machine image
> > 
> > 
> > @mjprilliman, can you attach your SAM file used to generate this and what resolution and magnification on your display are you using?
> > [Graphics_test.zip](https://github.com/NREL/wex/files/7892282/Graphics_test.zip)
> 
> image
> 
> Not sure about magnification, I don't have any Magnifiers on in Windows.

Sorry, scale and layout percentage (right click on desktop and select "Display settings"):
image

**Comment by cpaulgilman** [comment]
One more data point:

image

image

image

**Comment by mjprilliman** [comment]
image

**Comment by cpaulgilman** [comment]
I put some additional screenshots along with my Windows display setting in this PDF. This is on a version of SAM built off of this branch of WEX and Patch branches of SSC, SAM, and LK:

image

**Comment by sjanzou** [comment]
> I put some additional screenshots along with my Windows display setting in this PDF. This is on a version of SAM built off of this branch of WEX and Patch branches of SSC, SAM, and LK:
> 
> [windows-display-issues-from-paul.pdf](https://github.com/NREL/wex/files/7901159/windows-display-issues-from-paul.pdf)

@cpaulgilman, thanks for providing the screenshots... With wxWidgets 3.1.5 and latest updates using your screen resolutions, my loss diagram on the summary page is:
image

**Comment by sjanzou** [comment]
> > > @sjanzou are your results with this wex branch and everything else on patch? I am having trouble replicating the results on my Windows machine image
> > 
> > 
> > @mjprilliman, can you attach your SAM file used to generate this and what resolution and magnification on your display are you using?
> > [Graphics_test.zip](https://github.com/NREL/wex/files/7892282/Graphics_test.zip)
> 
> image
> 
> Not sure about magnification, I don't have any Magnifiers on in Windows.

@mjprilliman , thanks for providing the SAM project file... when I run on Windows 10 with the same display settings that you showed, I get the following parametric output graph:
image

**Comment by sjanzou** [comment]
@cpaulgilman , @mjprilliman please retest with latest updates to wex branch SAM_883. The anti aliasing issue on the plots has been resolved on all of the monitors and resolutions that I have tested. Thanks!

**Comment by cpaulgilman** [comment]
@sjanzou Agreed, the fonts look much nicer now. Lines and shading in tables is still too light to see.

**Comment by sjanzou** [comment]
> @sjanzou Agreed, the fonts look much nicer now. Lines and shading in tables is still too light to see.

@cpaulgilman, @mjprilliman can we close Sam 3883 with this pull request and create a different pull request for the shading on the row table (just on the statistics results tab)?

**Comment by mjprilliman** [comment]
> > @sjanzou Agreed, the fonts look much nicer now. Lines and shading in tables is still too light to see.
> 
> @cpaulgilman, @mjprilliman can we close Sam 3883 with this pull request and create a different pull request for the shading on the row table (just on the statistics results tab)?

I am not seeing much change in the fonts on my side but that may just be an issue with my settings. If it is working for everyone else I am fine with closing this PR.

image

**Comment by mjprilliman** [comment]
@sjanzou @cpaulgilman Disregard my last comment my branch was behind. Graphs look good on my end I think it would be good to merge this PR.

**Pull request merged**
