### PR TITLE
Pass -Wno-unused-but-set-variable for DView and Qhull sources

### PR DESCRIPTION
**Pull request by bje-**
Partial fix for issue #103

### CODE REVIEW

**Comment by bje-** [comment]
The whole WEX tree now compiles cleanly on Linux.

**Comment by bje-** [comment]
This build failed because the earlier pull requests (silencing various warnings) need to be merged first.

**Comment by bje-** [comment]
Note that this patch has failed the build because it depends on PR #102. We can re-run the build once #102 has been merged to demonstrate it is safe to apply.

**Comment by dguittet** [comment]
Thanks @bje-. I've rerun the build but getting new -Werrors: https://travis-ci.org/github/NREL/wex/jobs/696494044#L2467

**Comment by bje-** [comment]
Thanks, will investigate. I suspect I had too many parallel branches merged into my local `work` branch and lost track of which branches depended on others.

**Comment by bje-** [comment]
The problem was that I got overzealous and added `-Werror`, which means that this PR must be merged last. I have removed `-Werror` and that can be submitted as its own PR for this series. The build should go green now.

**Comment by bje-** [comment]
I have a better idea. Let's not pass `-Werror` at all, but instead have Travis CI compile with `-Werror`'. That way, users trying to compile SAM from source won't get torpedoed unnecessarily but we can still prevent warning-inducing changes from creeping into the code base.

**Comment by dguittet** [comment]
Thanks for fixing that. Looks like a build flag to Travis CI could do the trick: https://docs.platformio.org/en/latest/projectconf/section_env_build.html#build-flags

**Comment by bje-** [comment]
WEX is now warning free! Thanks.

**Comment by dguittet** [comment]
Thank YOU!

**Pull request merged**
